# Generated by Django 4.2.5 on 2023-09-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_uantity_orderitem_qantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qantity',
            new_name='quantity',
        ),
    ]
